### ISSUE TITLE
bug on the dependence 0.3.2 

### ISSUE THREAD

**Issue by VideoCassette** [JanusGraph/janusgraph#1693]
when I run the code 
     JanusGraph janusgraph = JanusGraphFactory.open("inmemory") to get the JanusGraph instance, it report a Error like NoClassDefFoundError:org/apache/tinkerpop/gremlin/process/traversal/step/OptionalStep and the OptionalStep is not created in the maven dependence
<dependence>
  <groupId>org.janusgraph</groupId>
 <artifactId>janusgraph-all</artifactId>
 <version>0.3.2</version>
</dependence>
and the same code works well in  the version 0.2.0, I thought this might be a bug in the version 0.3.2

**Comment by pluradj** [comment]
The correct artifact is `janusgraph-core`

https://github.com/JanusGraph/janusgraph/blob/v0.3.2/janusgraph-examples/example-common/pom.xml#L15-L17

**Comment by mbrukman** [comment]
@pluradj — looks like similar to [a question on SO][so-q]; do you want to post this answer there as well? I'd post it, but would like to make sure you get the credit for it.

[so-q]: https://stackoverflow.com/questions/57165882/how-can-i-get-the-janusgraph-instance-in-my-java-code
