### PR TITLE
Support JanusGraph OLAP with HBase TableSnapshotInputFormat #656

### LINKED ISSUE #656: Support JanusGraph OLAP with HBase TableSnapshotInputFormat
HBase has a TableSnapshotInputFormat which allows mapreduce job over snapshot files bypassing hbase server layer after a snapshot is taken of a table.  Bypassing HBase server calls will have a good performance boost for scan jobs.   MR job will consume a stable, read-only view of an HBase table directly off HDFS.  This can be used in place on online HBase cluster, or offline exported snapshot.

### PR DESCRIPTION
**Pull request by jerryjch**
Fixes #656 

Thank you for contributing to JanusGraph.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there an issue associated with this PR? Is it referenced in the commit message?
- [x] Does your PR body contain #xyz where xyz is the issue number you are trying to resolve?
- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?
- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you written and/or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE.txt file, including the main LICENSE.txt file in the root of this repository?
- [ ] If applicable, have you updated the NOTICE.txt file, including the main NOTICE.txt file found in the root of this repository?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java [hunk 1]
```diff
@@ -0,0 +1,171 @@
...
+ * <p>
+ * It is also required that Hadoop configuration directory, which contains
+ * core-site.xml, is in the classpath for access to the hadoop cluster. This
+ * requirement is similar to the configuration requirement for <a href=
+ * "http://tinkerpop.apache.org/docs/current/reference/#hadoop-gremlin">hadoop-gremlin</a>
+ * <p>
+ * Additionally, HBase configuration directory, which contains hbase-site.xml,
+ * should be placed in the classpath as well. If it is not, hbase.rootdir property
+ * needs to be set as a pass-through property in the graph property file. e.g.
+ * janusgraphmr.ioformat.conf.storage.hbase.ext.hbase.rootdir=/hbase
```
[the remark this answers is not in the document]
Comment (sjudeng) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: I wasn't able to get this to work by including hbase conf directory (which contains hbase-site.xml defining hbase.rootdir) on the classpath. Ultimately the only way I could get it to work was including the `hbase.rootdir` in the config as you document above.

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+        }
+    }
+
+    public RecordReader<ImmutableBytesWritable, Result> getTableReader() {
+        return tableReader;
+    }
+
+    public byte[] getEdgeStoreFamily() {
+        return edgeStoreFamily;
+    }
```
Comment (sjudeng) [inline janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: `getEdgeStoreFamily` and `getTableReader` don't appear to be used, can they be removed?

**Comment by jerryjch** [comment]
@sjudeng Thanks for the review.  I will address all the formatting and style changes.

File: janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java [hunk 3]
```diff
@@ -137,6 +137,17 @@
...
+    public static final ConfigOption<String> HBASE_SNAPSHOT =
+            new ConfigOption<>(HBASE_NS, "snapshot-name",
+            "The name of an exising HBase snapshot to be used by HBaseSnapshotInputFormat",
+            ConfigOption.Type.LOCAL, "janusgraph");
+    
+    public static final ConfigOption<String> HBASE_SNAPSHOT_RESTORE_DIR =
+            new ConfigOption<>(HBASE_NS, "snapshot-restore-dir",
+            "The tempoary directory to be used by HBaseSnapshotInputFormat to restore a snapshot." +
+            " This directory should be on the same File System as the HBase root dir.",
+            ConfigOption.Type.LOCAL, "/tmp");
```
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java]: I wonder what the best way is.  The directory can be on hdfs normally.

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: I probably have missed something, probably missed to read hbase conf, or add hbase conf resource to the final Configuration. I will correct it.  Thanks for the testing!

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+    private static final Logger log = LoggerFactory.getLogger(HBaseSnapshotBinaryInputFormat.class);
+
+    // Key for specifying the snapshot name. To be replaced by the constant in hbase package if it
+    // becomes public.
+    private static final String SNAPSHOT_NAME_KEY = "hbase.TableSnapshotInputFormat.snapshot.name";
+    // key for specifying the root dir of the restored snapshot. To be replaced by the constant
+    // in hbase package if it becomes public.
+    private static final String RESTORE_DIR_KEY = "hbase.TableSnapshotInputFormat.restore.dir";
+
+    private final TableSnapshotInputFormat tableSnapshotInputFormat = new TableSnapshotInputFormat();
```
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: Yep, the other inputformats do the same.

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+gremlin.hadoop.graphInputFormat=org.janusgraph.hadoop.formats.hbase.HBaseSnapshotInputFormat
+gremlin.hadoop.graphOutputFormat=org.apache.hadoop.mapreduce.lib.output.NullOutputFormat
+
+gremlin.hadoop.jarsInDistributedCache=true
+gremlin.hadoop.inputLocation=none
+gremlin.hadoop.outputLocation=target/output
+janusgraphmr.ioformat.conf.storage.backend=hbase
+janusgraphmr.ioformat.conf.storage.hbase.snapshot-name=snapshot1
+janusgraphmr.ioformat.conf.storage.hbase.snapshot-restore-dir=target/output
+janusgraphmr.ioformat.conf.storage.hostname=localhost
```
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties]: Will correct it.

[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties]: Will correct it.

File: janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java [hunk 6]
```diff
@@ -137,6 +137,17 @@
             " If this configuration option is not provided but graph.graphname is, the table will be set" +
             " to that value.",
             ConfigOption.Type.LOCAL, "janusgraph");
+    
+    public static final ConfigOption<String> HBASE_SNAPSHOT =
+            new ConfigOption<>(HBASE_NS, "snapshot-name",
+            "The name of an exising HBase snapshot to be used by HBaseSnapshotInputFormat",
+            ConfigOption.Type.LOCAL, "janusgraph");
```
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java]: Sounds good.

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java [hunk 7]
```diff
@@ -0,0 +1,171 @@
...
+                cfName = HBaseStoreManager.shortenCfName(shortCfMap, cfName);
+            } catch (PermanentBackendException e) {
+                throw new RuntimeException(e);
+            }
+        }
+        edgeStoreFamily = Bytes.toBytes(cfName);
+        scanner.addFamily(edgeStoreFamily);
+
+        // This is a workaround, to be removed when convertScanToString becomes public in hbase
+        // package.
```
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: You mean a hbase issue or Janusgraph issue?
There is HBase jira that has the fix.
https://issues.apache.org/jira/browse/HBASE-15223

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java (hunk 2 above)
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: Ok

Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: Ok

**Comment by jerryjch** [comment]
I will open a separate documentation ticket and find the appropriate place and content to document this feature.

File: janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (jerryjch) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: I will also open some hbase JIRA to make the snapshot property constants public

[the remark this answers is not in the document]
Comment (sjudeng) [reply janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java]: I was just thinking a JanusGraph issue to track it on our side.

File: janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (sjudeng) [reply janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java]: Is there a way to get a temporary HDFS directory if it's available or otherwise fall back on `java.io.tmpdir`? Either way not sure how you could express that as the default value instead of `"/tmp"` above. Maybe you could just omit the default and initialize it as appropriate in the constructor and then document the behavior as part of the parameter description string.

**Comment by jerryjch** [comment]
Need to rebase to the latest master ...

**Comment by jerryjch** [comment]
The solr7 module test failed in the last Travis job.  But the commit does not touch solr at all.
Retry.

**Comment by jerryjch** [comment]
I have tested with a hadoop/hbase cluster. It works fine now, either setting janusgraphmr.ioformat.conf.storage.hbase.ext.hbase.rootdir or setting CLASSPATH to include hbase conf dir. I will open some follow-up issues as said in the review.

**Comment by jerryjch** [comment]
@sjudeng Ping for more review!  Thanks.

**Comment by sjudeng** [comment]
Sorry for the delay. I've been having trouble getting OLAP running on Yarn again. I couldn't get it to work in the original test harness I reviewed under (e.g. CDH 5.7.0 Docker image). I updated to CDH 5.12.0 VM and then to Spark 2.2 and got further (OLAP bulk load works but not OLAP traversal). I don't think the issues are related to anything in this PR. If I can't get it to work with a little more time I'll try to at least test with Spark in local mode.

**Comment by jerryjch** [comment]
@sjudeng Thanks for your effort!

**Comment by jerryjch** [comment]
@sjudeng I see what you mean.  The PR to upgrade Tinkerpop to 3.3 was merged in between the last review and this one.

**Comment by jerryjch** [comment]
Thanks for the review and closing the PR. 
We should get some content of the github page you have into JanusGraph documentation.

**Comment by jerryjch** [comment]
```
 <!-- needed to resolve NoClassDefFoundError: org/apache/hadoop/hbase/mapreduce/TableInputFormat -->
     <dependency>
       <groupId>org.apache.hbase</groupId>
       <artifactId>hbase-server</artifactId>
```
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml#L62
Should we remove the optional and test scope for the hbase-server dependency?
Need to update it to hbase-shaded-server if we do make it non-optional.

**Comment by sjudeng** [comment]
The hbase-shaded-server might be okay to bundle in JanusGraph distributions. I'd be worried the unshaded version would pull in a large number of dependencies that could be disruptive to some (non-HBase) users. It's worth nothing that the added 50M hbase-shaded-server jar would push the JanusGraph distribution size over 300M. I think there's already a separate issue to track work to split distributions by backend to offer smaller (and cleaner) downloads targeting specific backend/indexing requirements.

I tested an OLAP traversal using hbase-shaded-server instead of hbase-server in the application jar and while the traveral was successful there was the following error when using the shaded dependency.

```
07:35:20 ERROR org.apache.spark.util.Utils - Uncaught exception in thread driver-revive-thread
org.apache.spark.SparkException: Could not find CoarseGrainedScheduler.
	at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:154) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.rpc.netty.Dispatcher.postOneWayMessage(Dispatcher.scala:134) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.rpc.netty.NettyRpcEnv.send(NettyRpcEnv.scala:186) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.rpc.netty.NettyRpcEndpointRef.send(NettyRpcEnv.scala:517) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(CoarseGrainedSchedulerBackend.scala:116) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:2.2.0.cloudera1]
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(CoarseGrainedSchedulerBackend.scala:116) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:2.2.0.cloudera1]
	at scala.Option.foreach(Option.scala:257) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anon$1$$anonfun$run$1.apply$mcV$sp(CoarseGrainedSchedulerBackend.scala:116) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:2.2.0.cloudera1]
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1317) ~[janusgraph-spark-0.0.1-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.cluster.CoarseGrainedSchedulerBackend$DriverEndpoint$$anon$1.run(CoarseGrainedSchedulerBackend.scala:115) [janusgraph-spark-0.0.1-SNAPSHOT.jar:2.2.0.cloudera1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by jerryjch** [comment]
The hbase-shaded-server jar is already in the distribution tarball, unfortunately.
https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml#L31
But it is declared as optional in the other module pom files.  It is probably done intentionally.  Then a user has to re-declared it in the user's pom as you did.
Yes, we can revisit it in the future.
I am not sure how the CoarseGrainedScheduler exception is related to this.
